Mission11_Thomas/Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace Mission11_Thomas.Models
{
    public class Book
    {
        [Key]
        public int BookID { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public string ISBN { get; set; }
        public string Classification { get; set; }
        public string Category { get; set; }
        public int PageCount { get; set; }
        public float Price { get; set; }

    }
}

Mission11_Thomas/Models/BookContext.cs
using Microsoft.EntityFrameworkCore;

namespace Mission11_Thomas.Models
{
    public class BookContext : DbContext
    {
        public BookContext (DbContextOptions<BookContext> options) : base(options) { }

        public DbSet<Book> Books { get; set;}
    }
}

Mission11_Thomas/Models/EFBookRepository.cs
namespace Mission11_Thomas.Models
{
    public class EFBookRepository : IBookRepository
    {
        private BookContext _context;
        public EFBookRepository(BookContext temp) {
            _context = temp;
        }
        public IQueryable<Book> Books => _context.Books;
    }
}

Mission11_Thomas/Models/IBookRepository.cs
namespace Mission11_Thomas.Models
{
    public interface IBookRepository
    {
        public IQueryable<Book> Books { get; }
    }
}

Mission11_Thomas/Models/ViewModels/BooksListViewModel.cs
namespace Mission11_Thomas.Models.ViewModels
{
    public class BooksListViewModel
    {
        public IQueryable<Book> Books { get; set;}

        public PaginationInfo PaginationInfo { get; set;} = new PaginationInfo();
    }
}

Mission11_Thomas/Models/ViewModels/PaginationInfo.cs
namespace Mission11_Thomas.Models.ViewModels
{
    public class PaginationInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalNumPages => (int) (Math.Ceiling((decimal) TotalItems / ItemsPerPage));
    }
}

Mission11_Thomas/Components/ProjectTypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Mission11_Thomas.Models;

namespace Mission11_Thomas.Components
{
    public class ProjectTypesViewComponent : ViewComponent
    {
        private IBookRepository _repo;

        //Constructor
        public ProjectTypesViewComponent(IBookRepository temp) 
        {
            _repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            var bookTypes = _repo.Books
                .Select(x => x.Title)
                .Distinct()
                .OrderBy(x => x)
                .ToList();

            return View(bookTypes);
        }
    }
}

Mission11_Thomas/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Mission11_Thomas.Models;
using Mission11_Thomas.Models.ViewModels;
using System.Diagnostics;

namespace Mission11_Thomas.Controllers
{
    public class HomeController : Controller
    {
        private IBookRepository _repo;

        public HomeController(IBookRepository temp)
        {
            _repo = temp;
        }

        public IActionResult Index(int pageNum)
        {
            int pageSize = 10;

            var data = new BooksListViewModel
            {
                Books = _repo.Books
                    .OrderBy(x => x.BookID)
                    .Skip((pageNum - 1) * pageSize)
                    .Take(pageSize),

                PaginationInfo = new PaginationInfo
                {
                    CurrentPage = pageNum,
                    ItemsPerPage = pageSize,
                    TotalItems = _repo.Books.Count()
                }
            };

            return View(data);
        }
    }
}

Mission11_Thomas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model BooksListViewModel

    <h1>AMAZON BOOKSTORE</h1>

    @foreach(Book b in Model.Books)
    {
        <partial name="ProjectSummary" model="b"/>
    }

<div page-model="@Model.PaginationInfo" page-action="Index" page-classes-enabled="true" page-class="btn" 
    page-class-normal="btn-outline-dark" page-class-selected="btn-primary" class="btn-group pull-right m-1"></div>

Mission11_Thomas/Views/Shared/Components/ProjectTypes/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IQueryable<string>

<div class="d-grid gap-2">
    <a class="btn btn-outline-secondary" asp-controller="Home" asp-action="Index">Home</a>

    @foreach (string title in Model ?? Enumerable.Empty<string>())
    {
        <a>@title</a>
    }
</div>

Mission11_Thomas/Views/Shared/ProjectSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Book

<div class="card m-1 p-1">
    <h4>
        @Model.Title
        <span class="badge rounded-pill bg-primary text-white float-end"><small>Price: @Model.Price</small></span>
    </h4>

    <ul>
        <li>Author: @Model.Author</li>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.ISBN</li>
        <li>Classification: @Model.Classification</li>
        <li>Category: @Model.Category</li>
        <li># Pages: @Model.PageCount</li>
    </ul>
</div>

Mission11_Thomas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mission11_Thomas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mission11_Thomas.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand m-lg-2">AMAZON BOOKS</span>
    </div>
    <div class="row m-1 p-1">
        <div class="col-3">
            <vc:project-types />
        </div>
    </div>

    <div class="container col-9">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>